apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: cars-devops
  labels:
    app: prometheus
spec:
  # ClusterIP: Prometheus acessível apenas internamente (item 3a da diretriz)
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
