apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: cars-devops
  labels:
    app: grafana
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus-service:9090
        isDefault: true
        access: proxy
        jsonData:
          timeInterval: "10s"
          httpMethod: POST
