apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: cars-devops
  labels:
    app: redis
spec:
  # ClusterIP: acessível apenas dentro do cluster (item 2c da diretriz)
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
