apiVersion: v1
kind: Service
metadata:
  name: cars-frontend-service
  namespace: cars-devops
  labels:
    app: cars-frontend
spec:
  # NodePort: expõe o frontend fora do cluster (item 2b da diretriz)
  type: NodePort
  selector:
    app: cars-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30030
      protocol: TCP
